"""Behaviour cloning: supervised pretraining of the SAC policy from demonstrations."""

from __future__ import annotations

import json

import numpy as np
import pytest

from tmai.agents.bc import pretrain_policy
from tmai.agents.normalize import NormalizingLearner
from tmai.agents.sac import SACLearner
from tmai.config import RunConfig
from tmai.training.demos import Demonstration


def _make_learner(observation_dim: int = 4, action_dim: int = 3, **sac_kwargs) -> SACLearner:
    from tmai.models.networks import NetworkConfig

    config = RunConfig().sac
    config.network = NetworkConfig(hidden_sizes=[32, 32])
    for key, value in sac_kwargs.items():
        setattr(config, key, value)
    return SACLearner(
        observation_dim=observation_dim,
        action_dim=action_dim,
        config=config,
        action_low=np.array([-1.0, 0.0, 0.0]),
        action_high=np.array([1.0, 1.0, 1.0]),
        seed=0,
    )


def _demo_from_policy(steps: int = 400, observation_dim: int = 4, seed: int = 1) -> Demonstration:
    """A demonstration generated by a fixed, learnable observation -> action mapping."""
    rng = np.random.default_rng(seed)
    observations = rng.normal(size=(steps, observation_dim)).astype(np.float32)
    steer = np.clip(observations[:, 0] * 0.8, -1.0, 1.0)
    throttle = np.clip(0.5 + 0.3 * observations[:, 1], 0.0, 1.0)
    actions = np.stack([steer, throttle, np.zeros(steps)], axis=1).astype(np.float32)
    return Demonstration(observations=observations, actions=actions)


class TestPretrainPolicy:
    def test_learns_the_demonstrated_mapping(self):
        learner = _make_learner()
        demos = _demo_from_policy()

        before = self._policy_mse(learner, demos)
        metrics = pretrain_policy(learner, demos, epochs=30, batch_size=64, lr=3e-3, seed=0)
        after = self._policy_mse(learner, demos)

        assert metrics["bc/samples"] == len(demos)
        assert metrics["bc/epochs"] == 30
        assert metrics["bc/final_train_loss"] < before
        assert after < before * 0.2  # a real fit, not a marginal improvement

    def test_val_loss_is_reported(self):
        learner = _make_learner()
        metrics = pretrain_policy(
            learner, _demo_from_policy(), epochs=2, val_fraction=0.2, seed=0
        )
        assert metrics["bc/val_loss"] == metrics["bc/val_loss"]  # not NaN
        assert metrics["bc/train_samples"] == 316  # purge gap before temporal validation
        assert metrics["bc/val_samples"] == 80
        assert metrics["bc/whole_file_validation"] == 0

    def test_validation_keeps_demonstration_files_separate(self, tmp_path):
        from tmai.training.demos import load_demonstrations

        learner = _make_learner()
        first = _demo_from_policy(steps=120, seed=2)
        second = _demo_from_policy(steps=80, seed=3)
        first_path = tmp_path / "first.jsonl"
        second_path = tmp_path / "second.jsonl"
        first.save(first_path)
        second.save(second_path)
        demos = load_demonstrations([first_path, second_path])

        metrics = pretrain_policy(learner, demos, epochs=1, val_fraction=0.2, seed=7)

        # A whole recording is reserved for validation, rather than randomly leaking
        # near-identical frames from each file into both partitions.
        assert metrics["bc/val_samples"] in {80, 120}
        assert metrics["bc/train_samples"] + metrics["bc/val_samples"] == 200
        assert metrics["bc/whole_file_validation"] == 1

    def test_actions_are_clipped_to_bounds(self):
        learner = _make_learner()
        demos = _demo_from_policy()
        demos.actions[:, 0] = 5.0  # out of range: the game read-back should never do this
        metrics = pretrain_policy(learner, demos, epochs=1, seed=0)
        assert np.isfinite(metrics["bc/final_train_loss"])

    def test_unwraps_normalising_learner(self):
        """A normalisation-wrapped learner is pretrained through its inner SAC policy."""
        sac = _make_learner()
        from tmai.env.normalization import RunningNormalizer

        wrapped = NormalizingLearner(sac, RunningNormalizer(4, warmup_steps=0))
        demos = _demo_from_policy()
        before = self._policy_mse(sac, demos)
        pretrain_policy(wrapped, demos, epochs=20, batch_size=64, lr=3e-3, seed=0)
        after = self._policy_mse(sac, demos)
        assert after < before * 0.2
        # Normalization statistics use only the training partition, not held-out frames.
        assert 0.85 * len(demos) < wrapped.normalizer.count < len(demos)

    def test_rejects_dimension_mismatch(self):
        learner = _make_learner(observation_dim=4)
        with pytest.raises(ValueError, match="observation_dim 6"):
            pretrain_policy(learner, _demo_from_policy(observation_dim=6))
        with pytest.raises(ValueError, match="action_dim"):
            pretrain_policy(
                _make_learner(action_dim=2),
                Demonstration(
                    observations=np.zeros((4, 4), dtype=np.float32),
                    actions=np.zeros((4, 3), dtype=np.float32),
                ),
            )

    def test_rejects_too_few_steps(self):
        learner = _make_learner()
        with pytest.raises(ValueError, match="at least 2"):
            pretrain_policy(
                learner,
                Demonstration(
                    observations=np.zeros((1, 4), dtype=np.float32),
                    actions=np.zeros((1, 3), dtype=np.float32),
                ),
            )

    def test_rejects_non_sac_learner(self):
        class NotSAC:
            observation_dim = 4
            action_dim = 3

        with pytest.raises(TypeError, match="SAC"):
            pretrain_policy(NotSAC(), _demo_from_policy())

    def test_deterministic_given_seed(self):
        def run():
            learner = _make_learner()
            pretrain_policy(learner, _demo_from_policy(), epochs=3, seed=7)
            return self._policy_mse(learner, _demo_from_policy())

        assert run() == pytest.approx(run())

    @staticmethod
    def _policy_mse(learner: SACLearner, demos: Demonstration) -> float:
        import torch

        with torch.no_grad():
            action, _ = learner.network.policy.sample(
                torch.as_tensor(demos.observations), deterministic=True
            )
        return float(((action.numpy() - demos.actions) ** 2).mean())


class TestTrainerIntegration:
    """BC runs inside train_from_config and is logged as an event."""

    def _config(self, tmp_path, demo_path, *, enabled=True, resume=None):
        config = RunConfig.from_yaml("tmai/configs/pipeline_smoke.yaml")
        config.train.total_steps = 200
        config.train.warmup_steps = 50
        config.train.eval_interval = 100
        config.train.held_out_eval_interval = 0
        config.train.checkpoint_interval = 100
        config.train.run_name = "bc-it"
        config.train.output_dir = str(tmp_path / "runs")
        config.train.record_replays = False
        config.bc.enabled = enabled
        config.bc.demo_paths = [str(demo_path)]
        config.bc.epochs = 2
        if resume:
            config.train.resume = resume
        return config

    def _write_demo(self, tmp_path, observation_dim: int) -> str:
        from tmai.training.factory import build_learner, build_library, build_multi_track_env

        config = RunConfig.from_yaml("tmai/configs/pipeline_smoke.yaml")
        library = build_library(config)
        env = build_multi_track_env(config, library, split="train", seed=0)
        try:
            learner = build_learner(env, config)
            dim = learner.observation_dim
        finally:
            env.close()
        assert dim == observation_dim
        rng = np.random.default_rng(0)
        demos = Demonstration(
            observations=rng.normal(size=(64, dim)).astype(np.float32),
            actions=np.tile([0.1, 0.8, 0.0], (64, 1)).astype(np.float32),
        )
        path = tmp_path / "demo.jsonl"
        demos.save(path)
        return str(path)

    def test_bc_pretrain_event_and_weights(self, tmp_path):
        from tmai.training.trainer import train_from_config

        config = RunConfig.from_yaml("tmai/configs/pipeline_smoke.yaml")
        # Discover the observation dim the same way the trainer will.
        from tmai.training.factory import build_learner, build_library, build_multi_track_env

        library = build_library(config)
        env = build_multi_track_env(config, library, split="train", seed=0)
        try:
            dim = build_learner(env, config).observation_dim
        finally:
            env.close()
        demo_path = self._write_demo(tmp_path, dim)

        config = self._config(tmp_path, demo_path)
        result = train_from_config(config)

        events = [
            json.loads(line)
            for line in (result.run_dir / "events.jsonl").read_text().splitlines()
            if '"bc_pretrain"' in line
        ]
        assert len(events) == 1
        event = events[0]
        assert event["bc/samples"] == 64
        assert event["bc/final_train_loss"] < 1.0

    def test_bc_skipped_when_resuming(self, tmp_path):
        from tmai.training.checkpoint import save_checkpoint
        from tmai.training.factory import build_learner, build_library, build_multi_track_env
        from tmai.training.trainer import train_from_config

        config = RunConfig.from_yaml("tmai/configs/pipeline_smoke.yaml")
        library = build_library(config)
        env = build_multi_track_env(config, library, split="train", seed=0)
        try:
            learner = build_learner(env, config)
            dim = learner.observation_dim
        finally:
            env.close()
        demo_path = self._write_demo(tmp_path, dim)

        # A checkpoint to resume from.
        checkpoint = save_checkpoint(
            tmp_path / "pre", step=0, learner=learner, config=config.to_dict()
        )
        resume_config = self._config(tmp_path, demo_path, resume=str(checkpoint))
        result = train_from_config(resume_config)
        events = [
            line
            for line in (result.run_dir / "events.jsonl").read_text().splitlines()
            if '"bc_pretrain"' in line
        ]
        assert events == []

    def test_bc_disabled_is_a_no_op(self, tmp_path):
        from tmai.training.factory import build_learner, build_library, build_multi_track_env
        from tmai.training.trainer import train_from_config

        config = RunConfig.from_yaml("tmai/configs/pipeline_smoke.yaml")
        library = build_library(config)
        env = build_multi_track_env(config, library, split="train", seed=0)
        try:
            dim = build_learner(env, config).observation_dim
        finally:
            env.close()
        demo_path = self._write_demo(tmp_path, dim)

        config = self._config(tmp_path, demo_path, enabled=False)
        result = train_from_config(config)
        events = [
            line
            for line in (result.run_dir / "events.jsonl").read_text().splitlines()
            if '"bc_pretrain"' in line
        ]
        assert events == []
